// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerAPIApp.DAL.Contexts;

#nullable disable

namespace ServerAPIApp.DAL.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    partial class BaseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.LanguageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_languages_code");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemDeletionRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("ProblemId");

                    b.ToTable("problem_deletion_requests", (string)null);
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletionDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_deadline");

                    b.Property<string>("DeletionJobId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("deletion_job_id");

                    b.Property<DateTimeOffset?>("DeletionScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_scheduled_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid?>("LastPublishedVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_published_version");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_problems_createdby");

                    b.HasIndex("DeletionJobId")
                        .HasDatabaseName("ix_problems_deletion_job_id");

                    b.HasIndex("LastPublishedVersionId");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_problems_slug");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean")
                        .HasColumnName("is_draft");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<int>("NumSubmissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("num_submissions");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("published_by");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<string>("TestTemplateKey")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("test_template_key");

                    b.Property<int>("TotalTests")
                        .HasColumnType("integer")
                        .HasColumnName("total_tests");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_problem_versions_createdat");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_problem_versions_createdby");

                    b.HasIndex("ProblemId");

                    b.HasIndex("PublishedBy");

                    b.ToTable("problem_versions", (string)null);
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemVersionLanguage", b =>
                {
                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("ArtifactsKey")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("artifacts_key");

                    b.Property<string>("EntryPoint")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entry_point");

                    b.HasKey("VersionId", "LanguageId");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_pvlang_languageid");

                    b.HasIndex("VersionId")
                        .HasDatabaseName("ix_pvlang_versionid");

                    b.ToTable("problem_languages", (string)null);
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.SubmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CpuTimeUs")
                        .HasColumnType("bigint")
                        .HasColumnName("cpu_time_us");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("PassedTests")
                        .HasColumnType("integer")
                        .HasColumnName("passed_tests");

                    b.Property<long>("PeakMemoryBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("peak_memory_bytes");

                    b.Property<Guid>("ProblemVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_version_id");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solution");

                    b.Property<string>("SolutionLanguage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("solution_language");

                    b.Property<int>("TotalTests")
                        .HasColumnType("integer")
                        .HasColumnName("total_tests");

                    b.Property<long>("WallTimeMs")
                        .HasColumnType("bigint")
                        .HasColumnName("wall_time_ms");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_submissions_createdat");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProblemVersionId")
                        .HasDatabaseName("ix_submissions_problemversion");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletionDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_deadline");

                    b.Property<string>("DeletionJobId")
                        .HasColumnType("text")
                        .HasColumnName("deletion_job_id");

                    b.Property<DateTimeOffset?>("DeletionScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_scheduled_at");

                    b.Property<string>("ExternalProviderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_provider_id");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_by");

                    b.HasKey("Id");

                    b.HasIndex("DeletionJobId")
                        .HasDatabaseName("ix_users_deletion_job_id");

                    b.HasIndex("ExternalProviderId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_external_provider_id");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemDeletionRequestEntity", b =>
                {
                    b.HasOne("ServerAPIApp.Domain.Entities.UserEntity", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerAPIApp.Domain.Entities.ProblemEntity", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiator");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemEntity", b =>
                {
                    b.HasOne("ServerAPIApp.Domain.Entities.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServerAPIApp.Domain.Entities.ProblemVersionEntity", "LastPublishedVersion")
                        .WithMany()
                        .HasForeignKey("LastPublishedVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ServerAPIApp.Domain.Entities.UserEntity", "Editor")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Editor");

                    b.Navigation("LastPublishedVersion");
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemVersionEntity", b =>
                {
                    b.HasOne("ServerAPIApp.Domain.Entities.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServerAPIApp.Domain.Entities.ProblemEntity", "Problem")
                        .WithMany("Versions")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerAPIApp.Domain.Entities.UserEntity", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublishedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("Problem");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemVersionLanguage", b =>
                {
                    b.HasOne("ServerAPIApp.Domain.Entities.LanguageEntity", "Language")
                        .WithMany("ProblemVersionLinks")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServerAPIApp.Domain.Entities.ProblemVersionEntity", "Version")
                        .WithMany("SupportedLanguages")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.SubmissionEntity", b =>
                {
                    b.HasOne("ServerAPIApp.Domain.Entities.UserEntity", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServerAPIApp.Domain.Entities.ProblemVersionEntity", "ProblemVersion")
                        .WithMany()
                        .HasForeignKey("ProblemVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("ProblemVersion");
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("ServerAPIApp.Domain.Entities.UserEntity", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServerAPIApp.Domain.Entities.UserEntity", "Editor")
                        .WithMany()
                        .HasForeignKey("ModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Editor");

                    b.Navigation("Initiator");
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.LanguageEntity", b =>
                {
                    b.Navigation("ProblemVersionLinks");
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemEntity", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ServerAPIApp.Domain.Entities.ProblemVersionEntity", b =>
                {
                    b.Navigation("SupportedLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
