services:
  server-api:
    container_name: api-app
    build:
      context: .
      dockerfile: ServerAPIApp/Dockerfile
    ports:
      - "12345:8080"
    volumes:
      - ./kubeconfig:/root/.kube:ro
    environment:
      - KUBECONFIG=/root/.kube/config