apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      serviceAccountName: api-server-sa
      containers:
      - name: api-server
        image: api-server:local
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DbConnectionString
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: DbConnectionString
        - name: Minio__AccessKey
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: AccessKey
        - name: Minio__SecretKey
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: SecretKey
        - name: KeycloakConfiguration__ApiClientSecret
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: ApiClientSecret
        - name: UseComposite
          valueFrom:
            configMapKeyRef:
              name: api-config   
              key: UseComposite 
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
