apiVersion: batch/v1
kind: Job
metadata:
  name: db-seeder
  namespace: postgresql   # <--- ensure job runs in the same ns as postgres-secret
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-seeder
        image: db-seeder:local
        env:
        - name: POSTGRES_HOST
          value: "postgres.postgresql.svc.cluster.local"   # correct namespace
        - name: POSTGRES_DB
          value: "postgresdb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: MINIO_ENDPOINT
          value: "minio.minio.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: SECRET_KEY
