apiVersion: batch/v1
kind: Job
metadata:
  name: db-seeder
  namespace: postgresql
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-seeder
        image: db-seeder:dev
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_HOST
          value: "postgres.postgresql.svc.cluster.local"
        - name: POSTGRES_DB
          value: "postgresdb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: ConnectionStrings__DbConnectionString
          valueFrom:
            secretKeyRef:
              name: seeder-secret
              key: ConnectionString
        - name: KeycloakConfiguration__ApiClientSecret
          valueFrom:
            secretKeyRef:
              name: seeder-secret
              key: ApiClientSecret
        - name: Minio__Endpoint
          value: "minio.minio.svc.cluster.local:9000"
        - name: Minio__AccessKey
          valueFrom:
            secretKeyRef:
              name: seeder-secret
              key: ACCESS_KEY
        - name: Minio__SecretKey
          valueFrom:
            secretKeyRef:
              name: seeder-secret
              key: SECRET_KEY
