apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  namespace: mssql
spec:
  clusterIP: None
  ports:
    - port: 1433
      name: tcp
  selector:
    app: mssql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: mssql
spec:
  serviceName: mssql-service
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-CU5-ubuntu-20.04
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
              name: tcp
          env:
            - name: ACCEPT_EULA
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: ACCEPT_EULA
            - name: MSSQL_PID
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: MSSQL_PID
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: mssqldata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
